name: Update README.md with recent blogs

on:
  schedule:
    - cron: 0 0 * * * # Run every day at midnight (UTC time)
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with recent blog posts
        uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://jasonet.co/rss.xml
          readme-section: feed
          max: 10
